float modf(float x, float *fp);
float ldexp(float x, int exp);
float floor(float d);
float ceil(float d);
float exp(float arg);
float frexp(float x, int *exp);
float log(float arg);
float log10(float arg);
float pow(float arg1, float arg2);
float fabs(float);
