#ifndef __PVSNESLIBVERSION_H__
#define __PVSNESLIBVERSION_H__

#define _PVSNESLIB_MAJOR_	4
#define _PVSNESLIB_MINOR_	0
#define _PVSNESLIB_PATCH_	0

#define _PVSNESLIB_STRING "PVSnesLib Release 4.0.0"

#endif // __PVSNESLIBVERSION_H__
