#ifndef __PVSNESLIBVERSION_H__
#define __PVSNESLIBVERSION_H__

#define _PVSNESLIB_MAJOR_	4
#define _PVSNESLIB_MINOR_	0
#define _PVSNESLIB_PATCH_	1

#define _PVSNESLIB_STRING_ "PVSnesLib V4.0.1"

#endif // __PVSNESLIBVERSION_H__
