#! /bin/sh

cd wlab
cp makefile.win32 makefile
make
cp wlab.exe ../binaries
make clean
cd ..

cd wlad
cp makefile.win32 makefile
make
cp wlad.exe ../binaries
make clean
cd ..

make clean
cp makefiles/makefile.win32.gb makefile
make
cp wla-gb.exe binaries

make clean
cp makefiles/makefile.win32.z80 makefile
make
cp wla-z80.exe binaries

make clean
cp makefiles/makefile.win32.6502 makefile
make
cp wla-6502.exe binaries

make clean
cp makefiles/makefile.win32.65c02 makefile
make
cp wla-65c02.exe binaries

make clean
cp makefiles/makefile.win32.6510 makefile
make
cp wla-6510.exe binaries

make clean
cp makefiles/makefile.win32.65816 makefile
make
cp wla-65816.exe binaries

make clean
cp makefiles/makefile.win32.spc700 makefile
make
cp wla-spc700.exe binaries

make clean
cp makefiles/makefile.win32.huc6280 makefile
make
cp wla-huc6280.exe binaries

make clean

cd wlalink
cp makefile.win32 makefile
make
cp wlalink.exe ../binaries
make clean
cd ..
