#ifndef __PVSNESLIBVERSION_H__
#define __PVSNESLIBVERSION_H__

#define _PVSNESLIB_MAJOR_	2
#define _PVSNESLIB_MINOR_	1
#define _PVSNESLIB_PATCH_	0

#define _PVSNESLIB_STRING "libSNES Release 2.1.0"

#endif // __PVSNESLIBVERSION_H__
